apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
spec:
  selector:
    matchLabels:
      app: spring-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
        - name: spring-demo
          image: spring-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080